# Generated by Django 2.2 on 2019-04-22 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlDigestionDBModel',
            fields=[
                ('url', models.TextField(primary_key=True, serialize=False)),
                ('digestion', models.TextField(default='')),
                ('author', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('publish_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('update_time', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
