# Generated by Django 2.2 on 2019-04-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190422_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='urldigestiondbmodel',
            name='url',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
