# Generated by Django 2.2 on 2019-04-22 19:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190422_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='id',
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.URLField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='DailyDigestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Site')),
                ('url_digestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UrlDigestionDBModel')),
            ],
            options={
                'unique_together': {('site', 'url_digestion')},
            },
        ),
    ]
