# Generated by Django 2.2 on 2019-04-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_site_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
